# .github/workflows/deploy.yml
name: Blue-Green Deployment

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to monitor

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Huawei Cloud CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        curl -LO "https://ap-southeast-3-hwcloudcli.obs.ap-southeast-3.myhuaweicloud.com/cli/latest/huaweicloud-cli-linux-amd64.tar.gz"
        tar -zxvf huaweicloud-cli-linux-amd64.tar.gz
        sudo mv $(pwd)/hcloud /usr/local/bin/
        yes y | hcloud auto-complete on
        hcloud version

    - name: Configure Huawei Cloud CLI profile
      run: |
        hcloud configure set --ak ${{ secrets.HUAWEI_CLOUD_ACCESS_KEY }} --sk ${{ secrets.HUAWEI_CLOUD_SECRET_KEY }} --region tr-west-1

    - name: Run deployment script
      run: |
        chmod +x blue-green-deployment.sh
        ./blue-green-deployment.sh
      env:
        LOAD_BALANCER_ID: "70ddfbb1-c01d-44b1-9878-e02f1d948bc5"
        POOL_ID: "5cd8db89-3072-4728-91da-f16ac11c422e"
        PROJECT_ID: "da9c89f493fb4554afab5f67a07ba4fd"
        REGION: "tr-west-1"
        SERVER1_ID: "2ca207a9-e3e9-4229-87a4-beb7ecbe7015"
        SERVER2_ID: "57e5bbbf-b623-4051-8253-3ae03ea5a944"
